import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import React from "react";

// No need to call them as functions, they're already initialized
const sans = GeistSans; // Changed this
const mono = GeistMono;

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${sans.variable} ${mono.variable} antialiased`}>
                <header className="bg-blue-600 text-white p-4">
                    <h1 className="text-2xl font-bold">Event Timeline</h1>
                </header>
                <main className="max-w-4xl mx-auto p-4">{children}</main>
                <footer className="bg-gray-200 text-center py-4">
                    <p>© 2024 Event Timeline</p>
                </footer>
            </body>
        </html>
    );
}
